modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="hollowsession"
version="1.0.0"
displayName="Hollow Session"
description='''Mod de horror ARG. Nada de monstros: apenas a sensação de que algo está errado com o seu jogo.'''

[[dependencies.hollowsession]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.hollowsession]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
